config/routes.rb
Tripsorter::Application.routes.draw do
  resources :boarding_passes

  root 'boarding_passes#index'

end

app/models/boarding_pass.rb
class BoardingPass < ActiveRecord::Base

def sort_trip
		a=BoardingPass.all
		
		route=""
		a.sort!{|a,b| a.destination <=> b.source}
		a.each do |route1|
		route+="From #{route1.source} take #{route1.transportation} to #{route1.destination} "
		end
		return route
		
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

app/controllers/boarding_passes_controller.rb
class BoardingPassesController < ApplicationController
  before_action :set_boarding_pass, only: [:show, :edit, :update, :destroy]

  # GET /boarding_passes
  # GET /boarding_passes.json
  def index
    @boarding_passes = BoardingPass.all
    @sortedtrips=BoardingPass.new
    @st =  @sortedtrips.sort_trip

  end

  # GET /boarding_passes/1
  # GET /boarding_passes/1.json
  def show
  end

  # GET /boarding_passes/new
  def new
    @boarding_pass = BoardingPass.new
  end

  # GET /boarding_passes/1/edit
  def edit
  end

  # POST /boarding_passes
  # POST /boarding_passes.json
  def create
    @boarding_pass = BoardingPass.new(boarding_pass_params)

    respond_to do |format|
      if @boarding_pass.save
        format.html { redirect_to @boarding_pass, notice: 'Boarding pass was successfully created.' }
        format.json { render action: 'show', status: :created, location: @boarding_pass }
      else
        format.html { render action: 'new' }
        format.json { render json: @boarding_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boarding_passes/1
  # PATCH/PUT /boarding_passes/1.json
  def update
    respond_to do |format|
      if @boarding_pass.update(boarding_pass_params)
        format.html { redirect_to @boarding_pass, notice: 'Boarding pass was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @boarding_pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boarding_passes/1
  # DELETE /boarding_passes/1.json
  def destroy
    @boarding_pass.destroy
    respond_to do |format|
      format.html { redirect_to boarding_passes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_boarding_pass
      @boarding_pass = BoardingPass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def boarding_pass_params
      params.require(:boarding_pass).permit(:source, :destination, :transportation, :seat, :gate, :counter)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boarding_passes_helper.rb
module BoardingPassesHelper
end

app/views/boarding_passes/_form.html.erb
<%= form_for(@boarding_pass) do |f| %>
  <% if @boarding_pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@boarding_pass.errors.count, "error") %> prohibited this boarding_pass from being saved:</h2>

      <ul>
      <% @boarding_pass.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br>
    <%= f.text_field :transportation %>
  </div>
  <div class="field">
    <%= f.label :seat %><br>
    <%= f.text_field :seat %>
  </div>
  <div class="field">
    <%= f.label :gate %><br>
    <%= f.text_field :gate %>
  </div>
  <div class="field">
    <%= f.label :counter %><br>
    <%= f.text_field :counter %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boarding_passes/edit.html.erb
<h1>Editing boarding_pass</h1>

<%= render 'form' %>

<%= link_to 'Show', @boarding_pass %> |
<%= link_to 'Back', boarding_passes_path %>

app/views/boarding_passes/index.html.erb
<h1>Listing boarding_passes</h1>

<table>
  <thead>
    <tr>
      <th>Source</th>
      <th>Destination</th>
      <th>Transportation</th>
      <th>Seat</th>
      <th>Gate</th>
      <th>Counter</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    
    <% @boarding_passes.each do |boarding_pass| %>
      <tr>
        <td><%= boarding_pass.source %></td>
        <td><%= boarding_pass.destination %></td>
        <td><%= boarding_pass.transportation %></td>
        <td><%= boarding_pass.seat %></td>
        <td><%= boarding_pass.gate %></td>
        <td><%= boarding_pass.counter %></td>
        <td><%= link_to 'Show', boarding_pass %></td>
        <td><%= link_to 'Edit', edit_boarding_pass_path(boarding_pass) %></td>
        <td><%= link_to 'Destroy', boarding_pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
    <%= @st%>
    
  </tbody>
</table>

<br>



<%= link_to 'New Boarding pass', new_boarding_pass_path %>

app/views/boarding_passes/new.html.erb
<h1>New boarding_pass</h1>

<%= render 'form' %>

<%= link_to 'Back', boarding_passes_path %>

app/views/boarding_passes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Source:</strong>
  <%= @boarding_pass.source %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @boarding_pass.destination %>
</p>

<p>
  <strong>Transportation:</strong>
  <%= @boarding_pass.transportation %>
</p>

<p>
  <strong>Seat:</strong>
  <%= @boarding_pass.seat %>
</p>

<p>
  <strong>Gate:</strong>
  <%= @boarding_pass.gate %>
</p>

<p>
  <strong>Counter:</strong>
  <%= @boarding_pass.counter %>
</p>

<%= link_to 'Edit', edit_boarding_pass_path(@boarding_pass) %> |
<%= link_to 'Back', boarding_passes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripsorter</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>